apiVersion: v1
kind: PersistentVolume
metadata:
    name: mariadb-pv
    labels:
      db: mariadb-data-volume
spec:
    storageClassName: manual
    capacity: 
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mariadb/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mariadb-backup-pv
    labels:
      db: mariadb-databackup-volume
spec:
    storageClassName: manual
    capacity: 
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mariadb/databackup"        
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#    name: mariadb-pvc
#spec:
#    storageClassName: manual
#    accessModes:
#        - ReadWriteOnce
#    resources:
#        requests:
#            storage: 1Gi
#    selector:
#        matchLabels:
#            db: mariadb
