apiVersion: com.gunjangarge.operator.mariadb/v1
kind: MariaDBMonitor
metadata:
  name: mariadb-monitor
  namespace: mariadb-ns
spec:
  # Add fields here
  size: 1
  data_source_name: "john:john123@(mariadb-service.mariadb-ns:3306)/sample"
  prometheus_mysqlexportor_image: "prom/mysqld-exporter"
  monitor_service_port: 32500