apiVersion: com.gunjangarge.operator.mariadb/v1
kind: MariaDB
metadata:
  name: mariadb-instance
spec:
  # Add fields here
  size: 1
  mysql_root_password: password
  db_image: mariadb:10.4
  mysql_database: sample1
  mysql_user: john1
  mysql_user_password: john1
  mysql_conn_service_port: 32000
  external_data_storage_persistent_volume_selector_label:
    db: mariadb-data-volume
  persistent_volume_claim:
    claim_size: 111Mi
    storage_class_name: manual
    access_mode: ReadWriteOnce