apiVersion: com.gunjangarge.operator.mariadb/v1
kind: MariaDBMonitor
metadata:
  name: backend-db-monitor
  namespace: mariadb-ns
spec:
  # Add fields here
  size: 1
  prometheus_mysqlexportor_image: "prom/mysqld-exporter"
  monitor_service_port: 32500