---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-operator
  labels:
    name: mariadb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mariadb-operator
  template:
    metadata:
      labels:
        name: mariadb-operator
    spec:
      serviceAccountName: mariadb-operator
      containers:
        - name: mariadb-operator
          # Replace this with the built image name
          image: quay.io/gunjangarge/mariadb-operator-ansible:v3
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
          env:
            - name: WATCH_NAMESPACE
              value: ""
              # valueFrom:
              #   fieldRef:
              #     fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mariadb-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_DEBUG_LOGS
              value: "True"
      volumes:
        - name: runner
          emptyDir: {}

