---
# tasks file for mariadb
- name: create mariadb
  community.kubernetes.k8s:
    definition: "{{ lookup('template', item) | from_yaml  }}"
  with_items:
    - mariadb-deployment.yaml.j2
    - mariadb-service.yaml.j2
  # - mariadb-pv-pvc.yaml.j2
    