---
# tasks file for mariadb
- name: create mariadb
  community.kubernetes.k8s:
    definition: "{{ lookup('template', item) | from_yaml  }}"
  with_items:
    - mariadb-secret.yaml.j2
    - mariadb-deployment.yaml.j2
    - mariadb-service.yaml.j2
    
- name: create pvc
  kubevirt_pvc:
    name: "{{meta.namespace}}-mariadb-pvc"
    namespace: "{{meta.namespace}}"
    labels:
      app: mariadb
      mariadb_cluster: "{{meta.namespace}}-{{meta.name}}"
    size: "{{persistent_volume_claim.claim_size}}"
    storage_class_name: "{{persistent_volume_claim.storage_class_name}}"
    access_modes:
        - "{{persistent_volume_claim.access_mode}}"
    selector:
        matchLabels:
            # db: mariadb
          "{{external_data_storage_persistent_volume_selector_label}}"
