---
# tasks file for mariadb
- name: create mariadb
  community.kubernetes.k8s:
    definition: "{{ lookup('template', item) | from_yaml  }}"
  with_items:
    - mariadb-deployment.yaml.j2
    - mariadb-service.yaml.j2
    # - mariadb-pv-pvc.yaml.j2
    
- name: create pvc
  kubevirt_pvc:
    name: "mariadb-persistent-volume-claim-{{meta.namespace}}"
    namespace: "{{meta.namespace}}"
    size: 100Mi
    storage_class_name: manual
    access_modes:
        - ReadWriteOnce
    selector:
        matchLabels:
            # db: mariadb
          "{{external_data_storage_persistent_volume_selector_label}}"
