apiVersion: com.gunjangarge.operator.mariadb/v1
kind: MariaDBRestore
metadata:
  name: mariad-brestore-instance
  namespace: mariadb-ns
spec:
  # Add fields here
  db_image: mariadb:10.4
  mysql_database_to_restore: sample
  mysql_user: john
  mysql_user_password: john123
  mysql_restore_sql_file: "mysqldump-sample-2020-May-18-063009UTC.sql"