apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "com.gunjangarge.operator.mariadb/v1",
          "kind": "MariaDB",
          "metadata": {
            "name": "mariadb-instance",
            "namespace": "mariadb-ns"
          },
          "spec": {
            "db_image": "mariadb:10.4",
            "external_data_storage_persistent_volume_selector_label": {
              "db": "mariadb-data-volume"
            },
            "mysql_conn_service_port": 32000,
            "mysql_database": "sample",
            "mysql_root_password": "password",
            "mysql_user": "john",
            "mysql_user_password": "john123",
            "persistent_volume_claim": {
              "access_mode": "ReadWriteOnce",
              "claim_size": "111Mi",
              "storage_class_name": "manual"
            },
            "size": 1
          }
        },
        {
          "apiVersion": "com.gunjangarge.operator.mariadb/v1",
          "kind": "MariaDBBackup",
          "metadata": {
            "name": "mariadbbackup-instance",
            "namespace": "mariadb-ns"
          },
          "spec": {
            "db_image": "mariadb:10.4",
            "external_data_storage_mariadb_backup_persistent_volume_selector_label": {
              "db": "mariadb-databackup-volume"
            },
            "mariadb_backup_persistent_volume_claim": {
              "access_mode": "ReadWriteOnce",
              "claim_size": "111Mi",
              "storage_class_name": "manual"
            },
            "mariadb_backup_schedule": "*/15 * * * *",
            "mariadb_mysqldump_options": "--flush-privileges --skip-lock-tables",
            "mysql_database_to_backup": "sample",
            "mysql_user": "john",
            "mysql_user_password": "john123"
          }
        },
        {
          "apiVersion": "com.gunjangarge.operator.mariadb/v1",
          "kind": "MariaDBRestore",
          "metadata": {
            "name": "mariadbrestore-instance",
            "namespace": "mariadb-ns"
          },
          "spec": {
            "db_image": "mariadb:10.4",
            "mysql_database_to_restore": "sample",
            "mysql_restore_sql_file": "mysqldump-sample-2020-May-18-063009UTC.sql",
            "mysql_user": "john",
            "mysql_user_password": "john123"
          }
        }
      ]
    capabilities: Full Lifecycle
    categories: Database
    certified: "false"
    containerImage: quay.io/gunjangarge/mariadb-operator-ansible:v3
    createdAt: "2020-04-21 11:17:00"
    description: Create mariadb server and database on Kubernetes
    repository: https://github.com/gunjangarge/mariadb-operator-ansible
    support: Gunjan Garge
  name: mariadb-operator-ansible.v0.0.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Represents a resource for managing MariaDB database
      displayName: MariaDB Operator using Ansible
      kind: MariaDB
      name: mariadbs.com.gunjangarge.operator.mariadb
      version: v1
    - description: Represents a resource for backup MariaDB database
      displayName: MariaDB Operator Backup using Ansible
      kind: MariaDBBackup
      name: mariadbbackups.com.gunjangarge.operator.mariadb
      version: v1
    - description: Represents a resource for restore MariaDB database
      displayName: MariaDB Operator Restore using Ansible
      kind: MariaDBRestore
      name: mariadbrestores.com.gunjangarge.operator.mariadb
      version: v1      
  description: This is mariadb operator using ansible
  displayName: Mariadb Operator Ansible
  icon:
  - base64data: ""
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - mariadb-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - com.gunjangarge.operator.mariadb
          resources:
          - '*'
          - mariadbbackups
          - mariadbrestores
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - batch
          resources:
          - cronjobs
          - jobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: mariadb-operator
      deployments:
      - name: mariadb-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: mariadb-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: mariadb-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: mariadb-operator
                - name: ANSIBLE_GATHERING
                  value: explicit
                - name: ANSIBLE_DEBUG_LOGS
                  value: "True"
                image: quay.io/gunjangarge/mariadb-operator-ansible:v3
                imagePullPolicy: IfNotPresent
                name: mariadb-operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: mariadb-operator
              volumes:
              - emptyDir: {}
                name: runner
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - mariadb operator ansible
  maintainers:
  - email: gunjangarge@gmail.com
    name: Gunjan Garge
  maturity: alpha
  provider:
    name: Gunjan Garge
  replaces: mariadb-operator-ansible.v0.0.2
  version: 0.0.3
