---
# tasks file for mariadbrestore
- name: Get backup volume claim from k8s_info
  k8s_info:
    api_version: v1
    kind: PersistentVolumeClaim
    label_selectors:
      - "purpose=databackup"
    namespace: "{{meta.namespace}}"
  register: backuppvcregister

# - name: Log backup volume claim from k8s_info
#   debug:
#     msg: "{{backuppvcregister}}"

- name: Set backup volume claim from k8s_info
  set_fact:
    pvc_name: "{{item}}"
  with_items : "{{ backuppvcregister | json_query('resources[0].metadata.name') }}"

- name: create job for mariadb restore
  community.kubernetes.k8s:
    definition: "{{ lookup('template', item) | from_yaml  }}"
  with_items:
    - mariadb-restore-job.yaml.j2
  when: 
    - mysql_restore_sql_file is defined
    - mysql_restore_sql_file != ""

- name: give error message when restore sql file is not present
  debug:
    msg: "Restore SQL file not present"
  when: mysql_restore_sql_file is undefined or mysql_restore_sql_file == ""