---
# tasks file for mariadbrestore
# - name: Get mariadb service ip address
#   k8s_info:
#     api_version: v1
#     kind: Service
#     name: mariadb-service
#     namespace: "{{meta.namespace}}"
#   register: mariadbserviceregister

# - name: Set mariadb service ip address from k8s_info
#   set_fact:
#     ip: "{{item}}"
#   with_items : "{{ mariadbserviceregister | json_query('resources[0].spec.clusterIP') }}"

- name: create job for mariadb restore
  community.kubernetes.k8s:
    definition: "{{ lookup('template', item) | from_yaml  }}"
  with_items:
    - mariadb-restore-job.yaml.j2
  when: 
    - mysql_restore_sql_file is defined
    - mysql_restore_sql_file != ""

- name: give error message when restore sql file is not present
  debug:
    msg: "Restore SQL file not present"
  when: mysql_restore_sql_file is undefined or mysql_restore_sql_file == ""